### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by theopolisme** [WPAFC/afch-rewrite#1]
- [x] offer a preferences interface, accessible through perhaps a gear icon in the upper lefthand corner?
- [x] allow reviewers to add categories to a page when accepting (get existing cats via Parsoid? see jquery.mwCoolCats in UploadWizard extension for ideas, perhaps)
- [ ] better spam blacklist behavior...
- [ ] ...

**Comment by APerson241** [comment]
Migrated remaining issue to #44.
