### ISSUE TITLE
Multiple decline reasons

### ISSUE THREAD

**Issue by enterprisey** [WPAFC/afch-rewrite#78]
The script should allow reviewers to decline a script for multiple reasons.

For example, if a draft reads like an advertisement _and_ is poorly sourced, selecting both reasons should add a decline box that includes comments for both `adv` and `v`.

This is one of the most-requested, perhaps _the_ most-requested, features for the script: see, for example, [here](https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation/Helper_script/Archive_2#Declining_a_submission_for_multiple_reasons) and [here](https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation/2013_3#Multiple_decline_reasons_at_once).

In order for the feature to be added, the following tasks need to be accomplished:
- [x] Change the submission template (specifically, [/declined](https://en.wikipedia.org/wiki/Template:AFC_submission/declined)) to support multiple reasons:
  - [x] Investigate whether to use another param (e.g. `{{{reason2}}}`) or use Lua to parse a comma-separated list of reasons.
    - [x] Resolve how to handle situations where both reasons need additional information (e.g. if both `dup` and `exists` are chosen, how are we going to store the duplicate article and the duplicate draft?)
    - [x] Investigate feasability of a Lua version.
    - [x] Investigate whether users would ever want to use three or more reasons at once.
  - [x] Implement multiple decline reasons in /declined.
- [ ] Update the script to support multiple reasons:
  - [x] Add the capability in the user interface to select multiple reasons (presumably by changing our existing Chosen.js instance to `multiple="true"`)
  - [ ] Allow the script to detect multiple selected reasons and update the decline template appropriately

**Comment by enterprisey** [comment]
This was done, but bugs remain in the implementation, for which I opened #120.
